USE [master]
GO

/****** Object:  Database [QMS]    Script Date: 24/2/2563 22:38:57 ******/
CREATE DATABASE [QMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QMS', FILENAME = N'C:\temp\QMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QMS_log', FILENAME = N'C:\temp\QMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [QMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QMS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QMS] SET  MULTI_USER 
GO

ALTER DATABASE [QMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QMS] SET QUERY_STORE = OFF
GO

USE [QMS]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [QMS] SET  READ_WRITE 
GO

